### ISSUE TITLE
Ezhil Lexer shoud be strictly limiting to English alphanumeric + Tamil identifiers

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/Ezhil-Lang#53]
Ezhil Lexer shoud be strictly limiting to English alphanumeric + Tamil identifiers
e.g. https://bitbucket.org/birkenfeld/pygments-main/pull-request/443/ezhil-language-lexer-for-pygments/diff#comment-4969520 demostrates a wrong acceptance of identifiers.

```  é.€ = 123```
```  பதிப்பி é.€ ```

**Comment by dscorbett** [comment]
This doesn’t entirely fix the issue. `x☺` is still legal, because it begins with an ASCII letter. `λஃ` is still legal, because it contains a Tamil grapheme.

**Comment by arcturusannamalai** [comment]
Sure thing; clearly the former is not a legal identifier name, while latter is valid. Let me see what I can do.

**Comment by dscorbett** [comment]
The latter is valid? But it contains a Greek letter.

**Comment by arcturusannamalai** [comment]
Sorry, I assumed it was a y or a h. It is \lambda and not valid indeed.
