### ISSUE TITLE
parsing nested if statements has bugs today

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/Ezhil-Lang#54]
'''Some flavors''' of if statements can show errors. We need exhaustive testing for this to validate the current implementation.

`e.g.` Can you make 2,3,4,5 ... n level nested if-statements and check if they parse and evaluate correctly ?

The following works, but we need more variants like this to be tested in suite;
@( 0 < 1 ) ஆனால்
     பதிப்பி "will print 0/1"	
     @( 0 < 3 ) ஆனால்
          பதிப்பி "will print 0/3"
   முடி
   @( 0 > 3 ) ஆனால்
          பதிப்பி "wont print 0/3"
    முடி
முடி

**Comment by msathia** [comment]
can it be elaborated? Unanble to see the issue

**Comment by arcturusannamalai** [comment]
Duplicated by parse error for while statement within a if statement. bug
#70
