### ISSUE TITLE
interpreter does not print 1 + 2 - 3

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/Ezhil-Lang#59]
```
$ ./ez 

>> x = 1 + 2 - 3
>>  printf("%d",x)
# x is assigned to 'None'

#whereas the following works OK
>> x = 1 + (2 - 3)
0
>>```

**Comment by msathia** [comment]
Not able to test it. Seems ok for me. 
எழில் 1>> x=1+2-3
எழில் 2>> x=1+(2-3)
எழில் 3>> x=1+2-3
எழில் 4>> printf("%d",x)
0
1
எழில் 5>> print("%d",x)
Exception in code, at line 5,  "print("%d",x)" 
 >>>>>>> Run-time error undefined function: ]print[ near ( 6, 5 ) 
எழில் 6>> x=1+(2-3)
எழில் 7>> printf("%d",x)
0
1
எழில் 8>>

**Comment by arcturusannamalai** [comment]
Thanks for verifying this Sathia.  I updated the description to make it a enhancement.

It seems like the code in https://github.com/arcturusannamalai/Ezhil-Lang/blob/master/ezhil/ezhil.py#L322 should be changed to say 
  **if rval != None:**

You can submit a pull request with unittest.
Thanks.
