### ISSUE TITLE
FAQs for Ezhil language

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/Ezhil-Lang#79]
Make a FAQs for Ezhil language addressing the basic question of encoding.
Recommend users to pursue the localhost installation.

**Comment by digital-carver** [comment]
Hi. Related to this, the actual command in webserver.sh: `cd ./web && python ../ezhil/EZWeb.py` actually works as it is in Windows. Just copying the .sh file as a .bat file and running it, cmd complains about the first line (`'#!' is not recognized`), but then goes on to run the second line and creates the webserver successfully. 

It might be worth adding a `webserver.bat` with just the second line of the shell script, for the sake of beginners that wish to use this recommended method in Windows.

**Comment by arcturusannamalai** [comment]
Thanks @digital-carver - please submit a PR.
