### ISSUE TITLE
can you create a contributor guidelines and a gitter channel. Which is speed up the development of this project.

### ISSUE THREAD

**Issue by plasmashadow** [arcturusannamalai/Ezhil-Lang#86]

**Comment by arcturusannamalai** [comment]
I am updating the CONTRIBUTING.txt file; 

Join the chat room on Gitter for arcturusannamalai/Ezhil-Lang: https://gitter.im/arcturusannamalai/Ezhil-Lang @gitchat வழியாக

**Comment by arcturusannamalai** [comment]
Closd by https://github.com/arcturusannamalai/Ezhil-Lang/commit/5775f702e4c1b13b1512e7174ef66771f091ddab
